### ISSUE TITLE
Docker  ENV settings 

### ISSUE THREAD

**Issue by alexsahka** [terafin/mqtt-venstar-bridge#3]
How to start in Docker? 
What ENV settings need to use?
Thanks.

**Comment by alexsahka** [comment]
OK, I figure out this by myself,
here is the list of Docker ENV settings:

VENSTAR_HOST (simple ip)
MQTT_HOST (must be with mqtt://ip or host)
TOPIC_PREFIX
MQTT_RETAIN
MQTT_USER  (optional if not secure mqtt server)
MQTT_PASS  (optional if not secure mqtt server)

**Comment by terafin** [comment]
I’m going to keep this open, to fix documentation here (and actually add some!)

**Comment by terafin** [comment]
Added to the main page
