### ISSUE TITLE
Query / Sensors calls missing

### ISSUE THREAD

**Issue by alexsahka** [terafin/mqtt-venstar-bridge#4]
Could you add Query / Sensors calls?
https://developer.venstar.com/restcalls.html#
![image](https://user-images.githubusercontent.com/7469537/73101633-ed004d00-3ea4-11ea-8fb2-d928214c2d58.png)

This request returns a list (array) of all the thermostat's sensors via an HTTP GET.

GET /query/sensors
Example:

http://192.168.1.100/query/sensors
Response
{
   "sensors": [
       {
           "name": "Thermostat",
	   "temp": 77
       },
       {
           "name": "Outdoor",
           "temp": 0
       }
   ]
}

**Comment by terafin** [comment]
Absolutely, will do my best to test it as well :) I don’t have any sensors.

**Comment by alexsahka** [comment]
I can test this, I have one sensor attached to my Venstar.

**Comment by terafin** [comment]
Should be resolved with 4d41b9e6d940292b73133332232c624e9587ad79

Please let me know if this doesn't work!
