### ISSUE TITLE
POST /settings calls missing

### ISSUE THREAD

**Issue by alexsahka** [terafin/mqtt-venstar-bridge#5]
This for enable/disable a schedule also away/home mode.
This is handy for switching back from manual mode.

https://developer.venstar.com/restcalls.html#
![image](https://user-images.githubusercontent.com/7469537/73108098-3dcb7200-3eb4-11ea-8580-57aa4ba049d3.png)

**Comment by terafin** [comment]
Done, all are supported now with: 1614e56b2026c18877429a1e65d88ba9cf00757c

Updated documentation on main page, let me know if you have any questions!

**Comment by alexsahka** [comment]
What is the Home/Away topic to post?

Im getting away status from /environment/thermostat/bedroom/away

Thank you!

**Comment by alexsahka** [comment]
I think I find the topic:
 /environment/thermostat/bedroom/setting/away/set   value is:  home or away
