### ISSUE TITLE
Minor /query/alerts and /query/runtimes is missing.

### ISSUE THREAD

**Issue by alexsahka** [terafin/mqtt-venstar-bridge#6]
To complete requests here is two not important but maybe someone can use it.
I personally use all of this with Node-Red but MQTT is way cleaner solution.
Thank you for your work!

/query/runtimes  (Im using this to see HeatPump / AUX heat run time, with NodeRed / InfluxDB / Grafana)
![image](https://user-images.githubusercontent.com/7469537/73108519-643ddd00-3eb5-11ea-991a-4ed1a1e4a6da.png)

/query/alerts   (Cool way to receive alerts from the thermostat)

**Comment by terafin** [comment]
My pleasure, how would you want to receive runtime info? Published hourly?

**Comment by alexsahka** [comment]
Currently, I'm doing every 24 hours, the thermostat is updating every midnight at 0:00.
So I'm updating it (for the last day only) at 12:05 am.

**Comment by terafin** [comment]
Would hourly work for you for runtime? Feels like daily is very specific :) I guess I can make it configurable!

Separately would love to learn how you're using the thermostats, and visualizing things - I don't run into many people that use them!

**Comment by alexsahka** [comment]
Hourly will work just fine, I can do record only after midnight.

I'm working on visualization but currently recording everything with NodeRed to InfluxDB and visualizing with Grafana. I'm planning to use Home Assistant in the future and insert Grafana into it.

**Comment by terafin** [comment]
Alerts and runtimes added here: 24f2bb81865bf49fc79628d8a8ae22eef0b61d45

**Comment by terafin** [comment]
(Runtime is hourly, plus once at startup)
