### ISSUE TITLE
Cannot send command

### ISSUE THREAD

**Issue by alexsahka** [terafin/mqtt-venstar-bridge#7]
Mqtt topic in docker:    sensors/inside/mainthermostat

Published
   topic: /sensors/inside/mainthermostat/fan/set
   value: on

Log from Docker (Fan is not switching ON)

MQTT Set Fan Mode: on
Starting queued timer
queued timer fired
updating with value: {"mode":3,"fan":0,"heattemp":66,"cooltemp":77}
 update succeeded: {"success":true}

**Comment by alexsahka** [comment]
Question: can I turn FAN on/off, or only auto/off?

**Comment by terafin** [comment]
Fixed in: 351215b49fa5e26d64d5df69cc376cb24d6f52ec

Fan can be:
off, on, auto

**Comment by terafin** [comment]
Let me know if it works, and re-open if not!

**Comment by alexsahka** [comment]
Yes, it works now!
Thank you!
