### ISSUE TITLE
Improvement request: /query/runtimes user call with MQTT.

### ISSUE THREAD

**Issue by alexsahka** [terafin/mqtt-venstar-bridge#8]
I played with /query/runtimes for a couple of days it works great thank you and I would like to ask for improvement.

Is it possible to call MQTT  /query/runtimes at user define time?
This way users can call for  /query/runtimes at the exact need time.

I think you can leave auto call as is, and add user request call with special MQTT topic.
with separate reply topic like /some_topic_prefix/somthing/runtimeuser

Again this is not important, just give more flexibility for the Venstar Bridge user to understand when AUX heater runs longer. (in my case to run AUX heater x4 times more expensive).

**Comment by terafin** [comment]
My pleasure, added in: 20dc2a63853c316012c759b77b177afba07127e5
Docs updated on main page

**Comment by alexsahka** [comment]
Thank you!
This is so quick!

**Comment by terafin** [comment]
Pleasure, an easy request :) Hopefully builds fast enough for you to pull it from docker!

**Comment by alexsahka** [comment]
When I query runtimes with:
topic: /venstar/bedroom/query
value: runtime

Im receiving the only timestamp
on topic: /venstar/bedroom/result/runtime
and sometimes heat1 time, but not full response.

**Comment by terafin** [comment]
Resolved in: e5d9ef12877da8ed5c5cb5d827ac27ba2dd62e83

**Comment by alexsahka** [comment]
Working, Thanks!
